//
//  CountryCode.swift
//  terncommerce
//
//  Created by 朱慧平 on 2018/1/30.
//  Copyright © 2018年 terncommerce. All rights reserved.
//

//import SwiftyJSON

var CountryCodeJsonSome: [[String:Any]] = [[String:Any]]()

let CountryCodeJson =  [
    [
        "en": "Angola",
        "es": "Angola",
        "zh": "安哥拉",
        "ar": "أنغولا",
        "locale": "AO",
        "code": 244,
        "en_n": "Move me",
        "ar_n": "أندوري"
    ],
    [
        "en": "Afghanistan",
        "es": "Afganistan",
        "zh": "阿富汗",
        "ar": "أفغانستان",
        "locale": "AF",
        "code": 93,
        "en_n": "Afghan",
        "ar_n": "أفغانستاني"
    ],
    [
        "en": "Albania",
        "es": "Albania",
        "zh": "阿尔巴尼亚",
        "ar": "ألبانيا",
        "locale": "AL",
        "code": 355,
        "en_n": "Albany",
        "ar_n": "ألباني"
    ],
    [
        "en": "Algeria",
        "es": "Algeria",
        "zh": "阿尔及利亚",
        "ar": "الجزائر",
        "locale": "DZ",
        "code": 213,
        "en_n": "Algerian",
        "ar_n": "جزائري"
    ],
    [
        "en": "Andorra",
        "es": "Andorra",
        "zh": "安道尔共和国",
        "ar": "أندورا",
        "locale": "AD",
        "code": 376,
        "en_n": "Andorra",
        "ar_n": "أندوري"
    ],
    [
        "en": "Antigua and Barbuda",
        "es": "Antigua y Barbuda",
        "zh": "安提瓜和巴布达",
        "ar": "أنتيغوا وبربودا",
        "locale": "AG",
        "code": 1268,
        "en_n": "Barbody",
        "ar_n": "بربودي",
    ],
    [
        "en": "Argentina",
        "es": "Argentina",
        "zh": "阿根廷",
        "locale": "AR",
        "code": 54,
        "ar": "الأرجنتين",
        "en_n": "Argentinian",
        "ar_n": "أرجنتيني",
    ],
    [
        "en": "Armenia",
        "es": "Armenia",
        "zh": "亚美尼亚",
        "locale": "AM",
        "code": 374,
        "ar": "أرمينيا",
        "en_n": "Armenian",
        "ar_n": "أرجنتيني",
    ],
    [
        "en": "Australia",
        "es": "Australia",
        "zh": "澳大利亚",
        "locale": "AU",
        "code": 61,
        "ar": "أستراليا",
        "en_n": "Australian",
        "ar_n": "أسترالي",
    ],
    [
        "en": "Austria",
        "es": "Austria",
        "zh": "奥地利",
        "locale": "AT",
        "code": 43,
        "ar": "النمسا",
        "en_n": "Austrian",
        "ar_n": "نمساوي",
    ],
    [
        "en": "Azerbaijan",
        "es": "Azerbaijan",
        "zh": "阿塞拜疆",
        "locale": "AZ",
        "code": 994,
        "ar": "أذربيجان",
        "en_n": "Azerbaijani",
        "ar_n": "أذربيجاني",
    ],
    [
        "en": "Bahamas",
        "es": "Bahamas",
        "zh": "巴哈马",
        "locale": "BS",
        "code": 1242,
        "ar": "الباهاماس",
        "en_n": "Bahamesi",
        "ar_n": "باهاميسي",
    ],
    [
        "en": "Bahrain",
        "es": "Bahrain",
        "zh": "巴林",
        "locale": "BH",
        "code": 973,
        "ar": "البحرين",
        "en_n": "Bahraini",
        "ar_n": "بحريني",
    ],
    [
        "en": "Bangladesh",
        "es": "Bangladesh",
        "zh": "孟加拉国",
        "locale": "BD",
        "code": 880,
        "ar": "بنغلاديش",
        "en_n": "Bangladeshi",
        "ar_n": "بنغلاديشي",
    ],
    [
        "en": "Barbados",
        "es": "Barbados",
        "zh": "巴巴多斯",
        "locale": "BB",
        "code": 1246,
        "ar": "بربادوس",
        "en_n": "Barbados",
        "ar_n": "بربادوسي",
    ],
    [
        "en": "Belarus",
        "es": "Belarus",
        "zh": "白俄罗斯",
        "locale": "BY",
        "code": 375,
        "ar": "روسيا البيضاء",
        "en_n": "Russian",
        "ar_n": "روسي",
    ],
    [
        "en": "Belgium",
        "es": "Belgica",
        "zh": "比利时",
        "locale": "BE",
        "code": 32,
        "ar": "بلجيكا",
        "en_n": "Belgian",
        "ar_n": "بلجيكي",
    ],
    [
        "en": "Belize",
        "es": "Belice",
        "zh": "伯利兹",
        "locale": "BZ",
        "code": 501,
        "ar": "بيليز",
        "en_n": "Belize",
        "ar_n": "بيليزي",
    ],
    [
        "en": "Benin",
        "es": "Benin",
        "zh": "贝宁",
        "locale": "BJ",
        "code": 229,
        "ar": "بنين",
        "en_n": "Benini",
        "ar_n": "بنيني",
    ],
    [
        "en": "Bhutan",
        "es": "Bhutan",
        "zh": "Bhutan",
        "locale": "BT",
        "code": 975,
        "ar": "بوتان",
        "en_n": "Botany",
        "ar_n": "بوتاني",
    ],
    [
        "en": "Bolivia",
        "es": "Bolivia",
        "zh": "玻利维亚",
        "locale": "BO",
        "code": 591,
        "ar": "بوليفيا",
        "en_n": "Bolivian",
        "ar_n": "بوليفي",
    ],
    [
        "en": "Botswana",
        "es": "Botswana",
        "zh": "博茨瓦纳",
        "locale": "BW",
        "code": 267,
        "ar": "بوتسوانا",
        "en_n": "Botswana",
        "ar_n": "بوتسواني",
    ],
    [
        "en": "Brazil",
        "es": "Brasil",
        "zh": "巴西",
        "locale": "BR",
        "code": 55,
        "ar": "البرازيل",
        "en_n": "Brazilian",
        "ar_n": "برازيلي",
    ],
    [
        "en": "Brunei",
        "es": "Brunei",
        "zh": "文莱",
        "locale": "BN",
        "code": 673,
        "ar": "بروني",
        "en_n": "Brunei",
        "ar_n": "بروني",
    ],
    [
        "en": "Bulgaria",
        "es": "Bulgaria",
        "zh": "保加利亚",
        "locale": "BG",
        "code": 359,
        "ar": "بلغاريا",
        "en_n": "Bulgarian",
        "ar_n": "بلغاري",
    ],
    [
        "en": "Burkina-faso",
        "es": "Burkina-faso",
        "zh": "布基纳法索",
        "locale": "BF",
        "code": 226,
        "ar": "بوركينا فاسو",
        "en_n": "Burkini",
        "ar_n": "بوركيني",
    ],
    [
        "en": "Burundi",
        "es": "Burundi",
        "zh": "布隆迪",
        "locale": "BI",
        "code": 257,
        "ar": "بوروندي",
        "en_n": "Burundi",
        "ar_n": "بورونيدي",
    ],
    [
        "en": "Cameroon",
        "es": "Camerun",
        "zh": "喀麦隆",
        "locale": "CM",
        "code": 237,
        "ar": "كاميرون",
        "en_n": "Cameroonian",
        "ar_n": "كاميروني",
    ],
    [
        "en": "Cambodia",
        "es": "Cambodia",
        "zh": "Cambodia",
        "locale": "KH",
        "code": 855,
        "ar": "كاميرون",
        "en_n": "Cambodian",
        "ar_n": "كاميروني",
    ],
    [
        "en": "Canada",
        "es": "Canada",
        "zh": "加拿大",
        "locale": "CA",
        "code": 1,
        "ar": "كندا",
        "en_n": "Canadian",
        "ar_n": "كندي",
    ],
    [
        "en": "Cape Verde",
        "es": "Cape Verde",
        "zh": "Cape Verde",
        "locale": "CV",
        "code": 238,
        "ar": "الرأس الأخضر",
        "en_n": "green head",
        "ar_n": "الرأس الأخضر",
    ],
    [
        "en": "Chad",
        "es": "Chad",
        "zh": "乍得",
        "locale": "TD",
        "code": 235,
        "ar": "تشاد",
        "en_n": "Chadian",
        "ar_n": "تشادي",
    ],
    [
        "en": "Chile",
        "es": "Chile",
        "zh": "智利",
        "locale": "CL",
        "code": 56,
        "ar": "شيلي",
        "en_n": "Chilean",
        "ar_n": "شيلي",
    ],
    [
        "en": "China",
        "es": "China",
        "zh": "中国",
        "locale": "CN",
        "code": 86,
        "ar": "الصين",
        "en_n": "Chinese",
        "ar_n": "صيني",
    ],
    [
        "en": "Colombia",
        "es": "Colombia",
        "zh": "哥伦比亚",
        "locale": "CO",
        "code": 57,
        "ar": "كولومبيا",
        "en_n": "Colombian",
        "ar_n": "كولومبي",
    ],
    [
        "en": "Congo",
        "es": "Congo",
        "zh": "刚果",
        "locale": "CG",
        "code": 242,
        "ar": "الكونغو",
        "en_n": "Kongi",
        "ar_n": "كونغي",
    ],
    [
        "en": "Costa Rica",
        "es": "Costa Rica",
        "zh": "哥斯达黎加",
        "locale": "CR",
        "code": 506,
        "ar": "كوستاريكا",
        "en_n": "Costa Rican",
        "ar_n": "كوستاريكي",
    ],
    [
        "en": "Cuba",
        "es": "Cuba",
        "zh": "古巴",
        "locale": "CU",
        "code": 53,
        "ar": "كوبا",
        "en_n": "Cuban",
        "ar_n": "كوبي",
    ],
    [
        "en": "Croatia",
        "es": "Croatia",
        "zh": "Croatia",
        "locale": "HR",
        "code": 385,
        "ar": "كرواتيا",
        "en_n": "Corati",
        "ar_n": "كوراتي",
    ],
    [
        "en": "Cyprus",
        "es": "Cyprus",
        "zh": "塞浦路斯",
        "locale": "CY",
        "code": 357,
        "ar": "قبرص",
        "en_n": "CY",
        "ar_n": "قبرصي",
    ],
    [
        "en": "Czech Republic",
        "es": "Republica Checa",
        "zh": "捷克",
        "locale": "CZ",
        "code": 420,
        "ar": "الجمهورية التشيكية",
        "en_n": "Czech",
        "ar_n": "تشيكي",
    ],
    [
        "en": "Denmark",
        "es": "Dinamarca",
        "zh": "丹麦",
        "locale": "DK",
        "code": 45,
        "ar": "الدانمارك",
        "en_n": "Dane",
        "ar_n": "دنماركي",
    ],
    [
        "en": "Djibouti",
        "es": "Djibouti",
        "zh": "吉布提",
        "locale": "DJ",
        "code": 253,
        "ar": "جيبوتي",
        "en_n": "Djibouti",
        "ar_n": "جيبوتي",
    ],
    [
        "en": "Dominica",
        "es": "Dominica",
        "zh": "Dominica",
        "locale": "DM",
        "code": 1,
        "ar": "الجمهورية الدومينيكية",
        "en_n": "Dominican",
        "ar_n": "دومينيكي",
    ],
    [
        "en": "Dominica Republic",
        "es": "Republica Dominica",
        "zh": "多米尼加共和国",
        "locale": "DO",
        "code": 1890,
        "ar": "دومينيكا",
        "en_n": "Dominican",
        "ar_n": "دومينيكي",
    ],
    [
        "en": "Ecuador",
        "es": "Ecuador",
        "zh": "厄瓜多尔",
        "locale": "EC",
        "code": 593,
        "ar": "إكوادور",
        "en_n": "Ecuadorian",
        "ar_n": "إكوادوري",
    ],
    [
        "en": "Egypt",
        "es": "Egipto",
        "zh": "埃及",
        "locale": "EG",
        "code": 20,
        "ar": "مصر",
        "en_n": "Egyptian",
        "ar_n": "مصري",
    ],
    [
        "en": "El Salvador",
        "es": "El Salvador",
        "zh": "萨尔瓦多",
        "locale": "SV",
        "code": 503,
        "ar": "إلسلفادور",
        "en_n": "Salvadoran",
        "ar_n": "سلفادوري",
    ],
    [
        "en": "Eritrea",
        "es": "Eritrea",
        "zh": "Eritrea",
        "locale": "ER",
        "code": 291,
        "ar": "إريتريا",
        "en_n": "Eritrean",
        "ar_n": "إريتيري",
    ],
    [
        "en": "Estonia",
        "es": "Estonia",
        "zh": "爱沙尼亚",
        "locale": "EE",
        "code": 372,
        "ar": "استونيا",
        "en_n": "Estonian",
        "ar_n": "استوني",
    ],
    [
        "en": "Ethiopia",
        "es": "Etiopia",
        "zh": "埃塞俄比亚",
        "locale": "ET",
        "code": 251,
        "ar": "أثيوبيا",
        "en_n": "Ethiopian",
        "ar_n": "أثيوبي",
    ],
    [
        "en": "Fiji",
        "es": "Fiji",
        "zh": "斐济",
        "locale": "FJ",
        "code": 679,
        "ar": "فيجي",
        "en_n": "Fiji",
        "ar_n": "فيجي",
    ],
    [
        "en": "Finland",
        "es": "Finlandia",
        "zh": "芬兰",
        "locale": "FI",
        "code": 358,
        "ar": "فنلندا",
        "en_n": "Finnish",
        "ar_n": "فنلندي",
    ],
    [
        "en": "France",
        "es": "Francia",
        "zh": "法国",
        "locale": "FR",
        "code": 33,
        "ar": "فرنسا",
        "en_n": "French",
        "ar_n": "فرنسي",
    ],
    [
        "en": "Gabon",
        "es": "Gabon",
        "zh": "加蓬",
        "locale": "GA",
        "code": 241,
        "ar": "الغابون",
        "en_n": "Gabon",
        "ar_n": "غابوني",
    ],
    [
        "en": "Gambia",
        "es": "Gambia",
        "zh": "冈比亚",
        "locale": "GM",
        "code": 220,
        "ar": "غامبيا",
        "en_n": "Gambian",
        "ar_n": "غامبي",
    ],
    [
        "en": "Georgia",
        "es": "Georgia",
        "zh": "格鲁吉亚",
        "locale": "GE",
        "code": 995,
        "ar": "جيورجيا",
        "en_n": "Gyorgy",
        "ar_n": "جيورجي",
    ],
    [
        "en": "Germany",
        "es": "Alemania",
        "zh": "德国",
        "locale": "DE",
        "code": 49,
        "ar": "ألمانيا",
        "en_n": "German",
        "ar_n": "ألماني",
    ],
    [
        "en": "Ghana",
        "es": "Ghana",
        "zh": "加纳",
        "locale": "GH",
        "code": 233,
        "ar": "غانا",
        "en_n": "Ghanaian",
        "ar_n": "غاني",
    ],
    [
        "en": "Greece",
        "es": "Grecia",
        "zh": "希腊",
        "locale": "GR",
        "code": 30,
        "ar": "اليونان",
        "en_n": "Greek",
        "ar_n": "يوناني",
    ],
    [
        "en": "Grenada",
        "es": "Granada",
        "zh": "格林纳达",
        "locale": "GD",
        "code": 1809,
        "ar": "غرينادا",
        "en_n": "Grenadi",
        "ar_n": "غرينادي",
    ],
    [
        "en": "Guatemala",
        "es": "Guatemala",
        "zh": "危地马拉",
        "locale": "GT",
        "code": 502,
        "ar": "غواتيمال",
        "en_n": "Guatemala",
        "ar_n": "غواتيمالي",
    ],
    [
        "en": "Guinea",
        "es": "Guinea",
        "zh": "几内亚",
        "locale": "GN",
        "code": 224,
        "ar": "غينيا",
        "en_n": "Guinness",
        "ar_n": "غيني",
    ],
    [
        "en": "Guinea-Bissau",
        "es": "Guinea-Bissau",
        "zh": "Guinea-Bissau",
        "locale": "GW",
        "code": 245,
        "ar": "غينيا-بيساو",
        "en_n": "Guinness",
        "ar_n": "غيني",
    ],
    [
        "en": "Guyana",
        "es": "Guyana",
        "zh": "圭亚那",
        "locale": "GY",
        "code": 592,
        "ar": "غيانا",
        "en_n": "Miss me",
        "ar_n": "غياني",
    ],
    [
        "en": "Haiti",
        "es": "Haiti",
        "zh": "海地",
        "locale": "HT",
        "code": 509,
        "ar": "هايتي",
        "en_n": "Haiti",
        "ar_n": "هايتي",
    ],
    [
        "en": "Honduras",
        "es": "Honduras",
        "zh": "洪都拉斯",
        "locale": "HN",
        "code": 504,
        "ar": "هندوراس",
        "en_n": "Honduras",
        "ar_n": "هندوراسي",
    ],
    [
        "en": "Hungary",
        "es": "Hungria",
        "zh": "匈牙利",
        "locale": "HU",
        "code": 36,
        "ar": "المجر",
        "en_n": "Stream",
        "ar_n": "مجري",
    ],
    [
        "en": "Iceland",
        "es": "Islandia",
        "zh": "冰岛",
        "locale": "IS",
        "code": 354,
        "ar": "آيسلندا",
        "en_n": "Icelandic",
        "ar_n": "آيسلندي",
    ],
    [
        "en": "India",
        "es": "India",
        "zh": "印度",
        "locale": "IN",
        "code": 91,
        "ar": "الهند",
        "en_n": "Indian",
        "ar_n": "هندي",
    ],
    [
        "en": "Indonesia",
        "es": "Indonesia",
        "zh": "印度尼西亚",
        "locale": "ID",
        "code": 62,
        "ar": "أندونيسيا",
        "en_n": "Indonesian",
        "ar_n": "أندونيسيي",
    ],
    [
        "en": "Iran",
        "es": "Iran",
        "zh": "伊朗",
        "locale": "IR",
        "code": 98,
        "ar": "إيران",
        "en_n": "Iranian",
        "ar_n": "إيراني",
    ],
    [
        "en": "Iraq",
        "es": "Iraq",
        "zh": "伊拉克",
        "locale": "IQ",
        "code": 964,
        "ar": "العراق",
        "en_n": "Iraqi",
        "ar_n": "عراقي",
    ],
    [
        "en": "Ireland",
        "es": "Irlanda",
        "zh": "爱尔兰",
        "locale": "IE",
        "code": 353,
        "ar": "إيرلندا",
        "en_n": "Irish",
        "ar_n": "إيرلندي",
    ],
    [
        "en": "Israel",
        "es": "Israel",
        "zh": "以色列",
        "locale": "IL",
        "code": 972,
        "ar": "إسرائيل",
        "en_n": "Israeli",
        "ar_n": "إسرائيلي",
    ],
    [
        "en": "Italy",
        "es": "Italia",
        "zh": "意大利",
        "locale": "IT",
        "code": 39,
        "ar": "إيطاليا",
        "en_n": "Italian",
        "ar_n": "إيطالي",
    ],
    [
        "en": "Jamaica",
        "es": "Jamaica",
        "zh": "牙买加",
        "locale": "JM",
        "code": 1876,
        "ar": "جمايكا",
        "en_n": "Jamaican",
        "ar_n": "جمايكي",
    ],
    [
        "en": "Japan",
        "es": "Japon",
        "zh": "日本",
        "locale": "JP",
        "code": 81,
        "ar": "اليابان",
        "en_n": "Japanese",
        "ar_n": "ياباني",
    ],
    [
        "en": "Jordan",
        "es": "Jordania",
        "zh": "约旦",
        "locale": "JO",
        "code": 962,
        "ar": "الأردن",
        "en_n": "Jordanian",
        "ar_n": "أردني",
    ],
    [
        "en": "Kazakstan",
        "es": "Kazajistán",
        "zh": "哈萨克斯坦",
        "locale": "KZ",
        "code": 327,
        "ar": "كازاخستان",
        "en_n": "Kazakh",
        "ar_n": "كازاخستاني",
    ],
    [
        "en": "Kenya",
        "es": "Kenia",
        "zh": "肯尼亚",
        "locale": "KE",
        "code": 254,
        "ar": "كينيا",
        "en_n": "Kenny",
        "ar_n": "كيني",
    ],
    [
        "en": "Kiribati",
        "es": "Kiribati",
        "zh": "Kiribati",
        "locale": "KI",
        "code": 686,
        "ar": "كيريباتي",
        "en_n": "Kiribati",
        "ar_n": "كيريباتي",
    ],
    [
        "en": "Kosovo",
        "es": "Kosovo",
        "zh": "Kosovo",
        "locale": "XK",
        "code": 383,
        "ar": "كوسوفو",
        "en_n": "Kosife",
        "ar_n": "كوسيفي",
    ],
    [
        "en": "Kuwait",
        "es": "Kuwait",
        "zh": "科威特",
        "locale": "KW",
        "code": 965,
        "ar": "الكويت",
        "en_n": "Kuwaiti",
        "ar_n": "كويتي",
    ],
    [
        "en": "Kyrgyzstan",
        "es": "Kirguistán",
        "zh": "吉尔吉斯坦",
        "locale": "KG",
        "code": 331,
        "ar": "قيرغيزستان",
        "en_n": "Kyrgyzstan",
        "ar_n": "قيرغيزستاني",
    ],
    [
        "en": "Laos",
        "es": "Laos",
        "zh": "老挝",
        "locale": "LA",
        "code": 856,
        "ar": "لاوس",
        "en_n": "Lao",
        "ar_n": "لاوسي",
    ],
    [
        "en": "Latvia",
        "es": "Letonia",
        "zh": "拉脱维亚",
        "locale": "LV",
        "code": 371,
        "ar": "لاتفيا",
        "en_n": "Latvian",
        "ar_n": "لاتيفي",
    ],
    [
        "en": "Lebanon",
        "es": "Libano",
        "zh": "黎巴嫩",
        "locale": "LB",
        "code": 961,
        "ar": "لبنان",
        "en_n": "Lebanese",
        "ar_n": "لبناني",
    ],
    [
        "en": "Lesotho",
        "es": "Lesoto",
        "zh": "莱索托",
        "locale": "LS",
        "code": 266,
        "ar": "ليسوتو",
        "en_n": "Leucite",
        "ar_n": "ليوسيتي",
    ],
    [
        "en": "Liberia",
        "es": "Liberia",
        "zh": "利比里亚",
        "locale": "LR",
        "code": 231,
        "ar": "ليبيريا",
        "en_n": "Liberian",
        "ar_n": "ليبيري",
    ],
    [
        "en": "Libya",
        "es": "Libia",
        "zh": "利比亚",
        "locale": "LY",
        "code": 218,
        "ar": "ليبيا",
        "en_n": "Libyan",
        "ar_n": "ليبي",
    ],
    [
        "en": "Liechtenstein",
        "es": "Liechtenstein",
        "zh": "列支敦士登",
        "locale": "LI",
        "code": 423,
        "ar": "ليختنشتين",
        "en_n": "Liechtenstein",
        "ar_n": "ليختنشتيني",
    ],
    [
        "en": "Lithuania",
        "es": "Lituania",
        "zh": "立陶宛",
        "locale": "LT",
        "code": 370,
        "ar": "لتوانيا",
        "en_n": "For my seconds",
        "ar_n": "لتوانيي",
    ],
    [
        "en": "Luxembourg",
        "es": "Luxemburgo",
        "zh": "卢森堡",
        "locale": "LU",
        "code": 352,
        "ar": "لوكسمبورغ",
        "en_n": "Luxembourgish",
        "ar_n": "لوكسمبورغي",
    ],
    [
        "en": "Madagascar",
        "es": "Madagascar",
        "zh": "马达加斯加",
        "locale": "MG",
        "code": 261,
        "ar": "مدغشقر",
        "en_n": "Madagascar",
        "ar_n": "مدغشقري",
    ],
    [
        "en": "Malawi",
        "es": "Malawi",
        "zh": "马拉维",
        "locale": "MW",
        "code": 265,
        "ar": "مالاوي",
        "en_n": "Malawi",
        "ar_n": "مالاوي",
    ],
    [
        "en": "Malaysia",
        "es": "Malasia",
        "zh": "马来西亚",
        "locale": "MY",
        "code": 60,
        "ar": "ماليزيا",
        "en_n": "Malaysian",
        "ar_n": "ماليزي",
    ],
    [
        "en": "Maldives",
        "es": "Maldivas",
        "zh": "马尔代夫",
        "locale": "MV",
        "code": 960,
        "ar": "المالديف",
        "en_n": "Maldives",
        "ar_n": "مالديفي",
    ],
    [
        "en": "Mali",
        "es": "Mali",
        "zh": "马里",
        "locale": "ML",
        "code": 223,
        "ar": "مالي",
        "en_n": "Financial",
        "ar_n": "مالي",
    ],
    [
        "en": "Malta",
        "es": "Malta",
        "zh": "马耳他",
        "locale": "MT",
        "code": 356,
        "ar": "مالطا",
        "en_n": "Maltese",
        "ar_n": "مالطي",
    ],
    [
        "en": "Mauritania",
        "es": "Marshall Islands",
        "zh": "Marshall Islands",
        "locale": "MH",
        "code": 692,
        "ar": "جزر مارشال",
        "en_n": "Marshallie",
        "ar_n": "مارشالي",
    ],
    [
        "en": "Mauritania",
        "es": "Mauritania",
        "zh": "Mauritania",
        "locale": "MR",
        "code": 222,
        "ar": "موريتانيا",
        "en_n": "Mauritanian",
        "ar_n": "موريتانيي",
    ],
    [
        "en": "Mauritius",
        "es": "Mauricio",
        "zh": "毛里求斯",
        "locale": "MU",
        "code": 230,
        "ar": "موريشيوس",
        "en_n": "Mauritius",
        "ar_n": "موريشيوسي",
    ],
    [
        "en": "Mexico",
        "es": "Mexico",
        "zh": "墨西哥",
        "locale": "MX",
        "code": 52,
        "ar": "المكسيك",
        "en_n": "Mexican",
        "ar_n": "مكسيكي",
    ],
    [
        "en": "Moldova",
        "es": "Moldova",
        "zh": "摩尔多瓦",
        "locale": "MD",
        "code": 373,
        "ar": "مولدافيا",
        "en_n": "Moldevi",
        "ar_n": "مولديفي",
    ],
    [
        "en": "Monaco",
        "es": "Monaco",
        "zh": "摩纳哥",
        "locale": "MC",
        "code": 377,
        "ar": "موناكو",
        "en_n": "Monique",
        "ar_n": "مونيكي",
    ],
    [
        "en": "Mongolia",
        "es": "Mongolia",
        "zh": "蒙古",
        "locale": "MN",
        "code": 976,
        "ar": "منغوليا",
        "en_n": "xanthous",
        "ar_n": "منغولي",
    ],
    [
        "en": "Morocco",
        "es": "Marruecos",
        "zh": "摩洛哥",
        "locale": "MA",
        "code": 212,
        "ar": "المغرب",
        "en_n": "Moroccan",
        "ar_n": "مغربي",
    ],
    [
        "en": "Myanmar",
        "es": "Mozambique",
        "zh": "莫桑比克",
        "locale": "MZ",
        "code": 258,
        "ar": "موزمبيق",
        "en_n": "Mozambique",
        "ar_n": "موزمبيقي",
    ],
    [
        "en": "Myanmar",
        "es": "Myanmar",
        "zh": "Myanmar",
        "locale": "MM",
        "code": 95,
        "ar": "ميانمار",
        "en_n": "Myanmar",
        "ar_n": "ميانماري",
    ],
    [
        "en": "Namibia",
        "es": "Namibia",
        "zh": "纳米比亚",
        "locale": "NA",
        "code": 264,
        "ar": "ناميبيا",
        "en_n": "Namibian",
        "ar_n": "ناميبي",
    ],
    [
        "en": "Nauru",
        "es": "Nauru",
        "zh": "瑙鲁",
        "locale": "NR",
        "code": 674,
        "ar": "نورو",
        "en_n": "My light",
        "ar_n": "نوري",
    ],
    [
        "en": "Nepal",
        "es": "Nepal",
        "zh": "尼泊尔",
        "locale": "NP",
        "code": 977,
        "ar": "نيبال",
        "en_n": "Nepalese",
        "ar_n": "نيبالي",
    ],
    [
        "en": "Netherlands",
        "es": "Países Bajos",
        "zh": "荷兰",
        "locale": "NL",
        "code": 31,
        "ar": "هولندا",
        "en_n": "Dutch",
        "ar_n": "هولندي",
    ],
    [
        "en": "New Zealand",
        "es": "Nueva Zelanda",
        "zh": "新西兰",
        "locale": "NZ",
        "code": 64,
        "ar": "نيوزيلندا",
        "en_n": "New Zealander",
        "ar_n": "نيوزيلندي",
    ],
    [
        "en": "Nicaragua",
        "es": "Nicaragua",
        "zh": "尼加拉瓜",
        "locale": "NI",
        "code": 505,
        "ar": "نيكاراجوا",
        "en_n": "Nicaragua",
        "ar_n": "نيكاراجوي",
    ],
    [
        "en": "Niger",
        "es": "Niger",
        "zh": "尼日尔",
        "locale": "NE",
        "code": 227,
        "ar": "النيجر",
        "en_n": "Nigerian",
        "ar_n": "نيجيري",
    ],
    [
        "en": "Nigeria",
        "es": "Nigeria",
        "zh": "尼日利亚",
        "locale": "NG",
        "code": 234,
        "ar": "نيجيريا",
        "en_n": "Nigerian",
        "ar_n": "نيجيري",
    ],
    [
        "en": "North Korea",
        "es": "Korea del Norte",
        "zh": "朝鲜",
        "locale": "KP",
        "code": 850,
        "ar": "كوريا الشمالية",
        "en_n": "Korean",
        "ar_n": "كوري",
    ],
    [
        "en": "Norway",
        "es": "Noruega",
        "zh": "挪威",
        "locale": "NO",
        "code": 47,
        "ar": "النرويج",
        "en_n": "Norwegian",
        "ar_n": "نرويجي",
    ],
    [
        "en": "Oman",
        "es": "Oman",
        "zh": "阿曼",
        "locale": "OM",
        "code": 968,
        "ar": "عمان",
        "en_n": "Omani",
        "ar_n": "عماني",
    ],
    [
        "en": "Pakistan",
        "es": "Pakistan",
        "zh": "巴基斯坦",
        "locale": "PK",
        "code": 92,
        "ar": "باكستان",
        "en_n": "Pakistani",
        "ar_n": "باكستاني",
    ],
    [
        "en": "Palau",
        "es": "Palau",
        "zh": "Palau",
        "locale": "PW",
        "code": 680,
        "ar": "بالاو",
        "en_n": "Palawy",
        "ar_n": "بالاوي",
    ],
    [
        "en": "Palestine",
        "es": "Palestine",
        "zh": "Palestine",
        "locale": "PS",
        "code": 970,
        "ar": "فلسطين",
        "en_n": "Palestinian",
        "ar_n": "فلسطيني",
    ],
    [
        "en": "Panama",
        "es": "Panama",
        "zh": "巴拿马",
        "locale": "PA",
        "code": 507,
        "ar": "بنما",
        "en_n": "Panamanian",
        "ar_n": "بنمي",
    ],
    [
        "en": "Papua New Guinea",
        "es": "Papua Nueva Guinea",
        "zh": "巴布亚新几内亚",
        "locale": "PG",
        "code": 675,
        "ar": "بابوا غينيا الجديدة",
        "en_n": "papal",
        "ar_n": "بابوي",
    ],
    [
        "en": "Paraguay",
        "es": "Paraguay",
        "zh": "巴拉圭",
        "locale": "PY",
        "code": 595,
        "ar": "باراغواي",
        "en_n": "Paraguay",
        "ar_n": "بارغاوي",
    ],
    [
        "en": "Peru",
        "es": "Peru",
        "zh": "秘鲁",
        "locale": "PE",
        "code": 51,
        "ar": "بيرو",
        "en_n": "Perry",
        "ar_n": "بيري",
    ],
    [
        "en": "Philippines",
        "es": "Filipinas",
        "zh": "菲律宾",
        "locale": "PH",
        "code": 63,
        "ar": "الفليبين",
        "en_n": "Filipino",
        "ar_n": "فلبيني",
    ],
    [
        "en": "Poland",
        "es": "Polonia",
        "zh": "波兰",
        "locale": "PL",
        "code": 48,
        "ar": "بولونيا",
        "en_n": "Polynes",
        "ar_n": "بوليني",
    ],
    [
        "en": "Portugal",
        "es": "Portugal",
        "zh": "葡萄牙",
        "locale": "PT",
        "code": 351,
        "ar": "البرتغال",
        "en_n": "Portuguese",
        "ar_n": "برتغالي",
    ],
    [
        "en": "Qatar",
        "es": "Qatar",
        "zh": "卡塔尔",
        "locale": "QA",
        "code": 974,
        "ar": "قطر",
        "en_n": "diagonal",
        "ar_n": "قطري",
    ],
    [
        "en": "Romania",
        "es": "Rumania",
        "zh": "罗马尼亚",
        "locale": "RO",
        "code": 40,
        "ar": "رومانيا",
        "en_n": "Romanian",
        "ar_n": "روماني",
    ],
    [
        "en": "Russia",
        "es": "Rusia",
        "zh": "俄罗斯",
        "locale": "RU",
        "code": 7,
        "ar": "روسيا",
        "en_n": "Russian",
        "ar_n": "روسي",
    ],
    [
        "en": "Rwanda",
        "es": "Rwanda",
        "zh": "Rwanda",
        "locale": "RW",
        "code": 250,
        "ar": "رواندا",
        "en_n": "Russian",
        "ar_n": "رواندا",
    ],
    [
        "en": "Samoa",
        "es": "Samoa",
        "zh": "西萨摩亚",
        "locale": "WS",
        "code": 685,
        "ar": "ساموا",
        "en_n": "Samui",
        "ar_n": "ساموي",
    ],
    [
        "en": "San Marino",
        "es": "San Marino",
        "zh": "圣马力诺",
        "locale": "SM",
        "code": 378,
        "ar": "سان مارينو",
        "en_n": "Marini",
        "ar_n": "ماريني",
    ],
    [
        "en": "Sao Tome and Principe",
        "es": "Santo Tomé y Príncipe",
        "zh": "圣多美和普林西比",
        "locale": "ST",
        "code": 239,
        "ar": "ساو تومي وبرينسيبي",
        "en_n": "Sao Tome and Principe",
        "ar_n": "ساو تومي وبرينسيبي",
    ],
    [
        "en": "Saudi Arabia",
        "es": "Arabia Saudita",
        "zh": "沙特阿拉伯",
        "locale": "SA",
        "code": 966,
        "ar": "المملكة العربية السعودية",
        "en_n": "Saudi",
        "ar_n": "سعودي",
    ],
    [
        "en": "Senegal",
        "es": "Senegal",
        "zh": "塞内加尔",
        "locale": "SN",
        "code": 221,
        "ar": "السنغال",
        "en_n": "Senegalese",
        "ar_n": "سنغالي",
    ],
    [
        "en": "Serbia",
        "es": "Serbia",
        "zh": "Serbia",
        "locale": "RS",
        "code": 381,
        "ar": "صربيا",
        "en_n": "Serbian",
        "ar_n": "صربي",
    ],
    [
        "en": "Seychelles",
        "es": "Seychelles",
        "zh": "塞舌尔",
        "locale": "SC",
        "code": 248,
        "ar": "سيشيل",
        "en_n": "Seychelles",
        "ar_n": "سيشيلي",
    ],
    [
        "en": "Sierra Leone",
        "es": "Sierra Leona",
        "zh": "塞拉利昂",
        "locale": "SL",
        "code": 232,
        "ar": "سيراليون",
        "en_n": "Sierra Leone",
        "ar_n": "سيراليوني",
    ],
    [
        "en": "Singapore",
        "es": "Singapur",
        "zh": "新加坡",
        "locale": "SG",
        "code": 65,
        "ar": "سنغافورة",
        "en_n": "Singaporean",
        "ar_n": "سنغافوري",
    ],
    [
        "en": "Slovakia",
        "es": "Eslovaquia",
        "zh": "斯洛伐克",
        "locale": "SK",
        "code": 421,
        "ar": "سلوفاكيا",
        "en_n": "Solvaki",
        "ar_n": "سولفاكي",
    ],
    [
        "en": "Slovenia",
        "es": "Eslovenia",
        "zh": "斯洛文尼亚",
        "locale": "SI",
        "code": 386,
        "ar": "سلوفينيا",
        "en_n": "Sulfini",
        "ar_n": "سولفيني",
    ],
    [
        "en": "Solomon Islands",
        "es": "Islas Salomón",
        "zh": "所罗门群岛",
        "locale": "SB",
        "code": 677,
        "ar": "جزر سليمان",
        "en_n": "Solomon Islands",
        "ar_n": "جزر سليمان",
    ],
    [
        "en": "Somali",
        "es": "Somalia",
        "zh": "索马里",
        "locale": "SO",
        "code": 252,
        "ar": "الصومال",
        "en_n": "Somali",
        "ar_n": "صومالي",
    ],
    [
        "en": "South Africa",
        "es": "Sudafrica",
        "zh": "南非",
        "locale": "ZA",
        "code": 27,
        "ar": "جنوب أفريقيا",
        "en_n": "African",
        "ar_n": "أفريقي",
    ],
    [
        "en": "South Sudan",
        "es": "South Sudan",
        "zh": "South Sudan",
        "locale": "SS",
        "code": 211,
        "ar": "السودان الجنوبي",
        "en_n": "Black",
        "ar_n": "سوادني",
    ],
    [
        "en": "Spain",
        "es": "España",
        "zh": "西班牙",
        "locale": "ES",
        "code": 34,
        "ar": "إسبانيا",
        "en_n": "Spanish",
        "ar_n": "إسباني",
    ],
    [
        "en": "Sri Lanka",
        "es": "Sri Lanka",
        "zh": "斯里兰卡",
        "locale": "LK",
        "code": 94,
        "ar": "سريلانكا",
        "en_n": "Sri Lankan",
        "ar_n": "سريلانكي",
    ],
    [
        "en": "Sudan",
        "es": "Sudan",
        "zh": "苏丹",
        "locale": "SD",
        "code": 249,
        "ar": "السودان",
        "en_n": "Black",
        "ar_n": "سوادني",
    ],
    [
        "en": "South Korea",
        "es": "South Korea",
        "zh": "South Korea",
        "locale": "KR",
        "code": 82,
        "ar": "كوريا الجنوبية",
        "en_n": "Korean",
        "ar_n": "كوري",
    ],
    [
        "en": "Suriname",
        "es": "Suriname",
        "zh": "苏里南",
        "locale": "SR",
        "code": 597,
        "ar": "سورينام",
        "en_n": "Suriname",
        "ar_n": "سورينامي",
    ],
    [
        "en": "Swaziland",
        "es": "Suazilandia",
        "zh": "斯威士兰",
        "locale": "SZ",
        "code": 268,
        "ar": "سوازيلند",
        "en_n": "Swaziland",
        "ar_n": "سوازيلندي",
    ],
    [
        "en": "Sweden",
        "es": "Suecia",
        "zh": "瑞典",
        "locale": "SE",
        "code": 46,
        "ar": "السويد",
        "en_n": "suede",
        "ar_n": "سويدي",
    ],
    [
        "en": "Switzerland",
        "es": "Suiza",
        "zh": "瑞士",
        "locale": "CH",
        "code": 41,
        "ar": "سويسرا",
        "en_n": "Swiss",
        "ar_n": "سويسري",
    ],
    [
        "en": "Syria",
        "es": "Siria",
        "zh": "叙利亚",
        "locale": "SY",
        "code": 963,
        "ar": "سوريا",
        "en_n": "Syrian",
        "ar_n": "سوري",
    ],
    [
        "en": "Taiwan",
        "es": "Taiwan",
        "zh": "台湾省",
        "locale": "TW",
        "code": 886,
        "ar": "تايوان",
        "en_n": "Taiwanese",
        "ar_n": "تايواني",
    ],
    [
        "en": "Tajikstan",
        "es": "Tajikstan",
        "zh": "塔吉克斯坦",
        "locale": "TJ",
        "code": 992,
        "ar": "طاجيكستان",
        "en_n": "Tajikistan",
        "ar_n": "طاجيكستاني",
    ],
    [
        "en": "Tanzania",
        "es": "Tanzania",
        "zh": "坦桑尼亚",
        "locale": "TZ",
        "code": 255,
        "ar": "تنزانيا",
        "en_n": "Tanzanian",
        "ar_n": "تنزانيي",
    ],
    [
        "en": "Thailand",
        "es": "Tailandia",
        "zh": "泰国",
        "locale": "TH",
        "code": 66,
        "ar": "تايلند",
        "en_n": "Thai",
        "ar_n": "تايلندي",
    ],
    [
        "en": "Timor-Leste",
        "es": "Timor-Leste",
        "zh": "Timor-Leste",
        "locale": "TL",
        "code": 670,
        "ar": "تيمور الشرقية",
        "en_n": "Timur",
        "ar_n": "تيموري",
    ],
    [
        "en": "Togo",
        "es": "Togo",
        "zh": "多哥",
        "locale": "TG",
        "code": 228,
        "ar": "توغو",
        "en_n": "Togie",
        "ar_n": "توغي",
    ],
    [
        "en": "Tonga",
        "es": "Tonga",
        "zh": "汤加",
        "locale": "TO",
        "code": 676,
        "ar": "تونغا",
        "en_n": "Tongi",
        "ar_n": "تونغي",
    ],
    [
        "en": "Trinidad and Tobago",
        "es": "Trinidad y Tobago",
        "zh": "特立尼达和多巴哥",
        "locale": "TT",
        "code": 1809,
        "ar": "ترينيداد وتوباغو",
        "en_n": "Trinidad and Tobago",
        "ar_n": "ترينيداد وتوباغو",
    ],
    [
        "en": "Tunisia",
        "es": "Tunisia",
        "zh": "突尼斯",
        "locale": "TN",
        "code": 216,
        "ar": "تونس",
        "en_n": "Tunisian",
        "ar_n": "تونسي",
    ],
    [
        "en": "Turkey",
        "es": "Turquia",
        "zh": "土耳其",
        "locale": "TR",
        "code": 90,
        "ar": "تركيا",
        "en_n": "Turkish",
        "ar_n": "تركي",
    ],
    [
        "en": "Turkmenistan",
        "es": "Turkmenistan",
        "zh": "土库曼斯坦",
        "locale": "TM",
        "code": 993,
        "ar": "تركمانستان",
        "en_n": "Turkmenistan",
        "ar_n": "تركمانستاني",
    ],
    [
        "en": "Tuvalu",
        "es": "Turkmenistan",
        "zh": "土库曼斯坦",
        "locale": "TV",
        "code": 688,
        "ar": "توفالو",
        "en_n": "Tuvali",
        "ar_n": "توفالي",
    ],
    [
        "en": "Uganda",
        "es": "Uganda",
        "zh": "乌干达",
        "locale": "UG",
        "code": 256,
        "ar": "أوغندا",
        "en_n": "Ugandan",
        "ar_n": "أوغندي",
    ],
    [
        "en": "Ukraine",
        "es": "Ucrania",
        "zh": "乌克兰",
        "locale": "UA",
        "code": 380,
        "ar": "أوكرانيا",
        "en_n": "Ukrainian",
        "ar_n": "أوكراني",
    ],
    [
        "en": "United Arab Emirates",
        "es": "Emiratos Arabes Unidos",
        "zh": "阿拉伯联合酋长国",
        "locale": "AE",
        "code": 971,
        "ar": "الإمارات العربية المتحدة",
        "en_n": "Emirati",
        "ar_n": "إماراتي",
    ],
    [
        "en": "United Kingdom",
        "es": "Reino unido",
        "zh": "英国",
        "locale": "GB",
        "code": 44,
        "ar": "المملكة المتحدة",
        "en_n": "British",
        "ar_n": "بريطاني",
    ],
    [
        "en": "United States",
        "es": "Estados Unidos",
        "zh": "美国",
        "locale": "US",
        "code": 1,
        "ar": "الولايات المتحدة",
        "en_n": "American",
        "ar_n": "أمريكي",
    ],
    [
        "en": "Uruguay",
        "es": "Uruguay",
        "zh": "乌拉圭",
        "locale": "UY",
        "code": 598,
        "ar": "أورغواي",
        "en_n": "Uruguay",
        "ar_n": "أورغواي",
    ],
    [
        "en": "Uzbekistan",
        "es": "Uzbekistan",
        "zh": "乌兹别克斯坦",
        "locale": "UZ",
        "code": 233,
        "ar": "أوزباكستان",
        "en_n": "Uzbekistani",
        "ar_n": "أوزباكستاني",
    ],
    [
        "en": "Vanuatu",
        "es": "Vanuatu",
        "zh": "Vanuatu",
        "locale": "VU",
        "code": 678,
        "ar": "فانواتو",
        "en_n": "Vanuatie",
        "ar_n": "فانواتي",
    ],
    [
        "en": "Venezuela",
        "es": "Venezuela",
        "zh": "委内瑞拉",
        "locale": "VE",
        "code": 58,
        "ar": "فنزويلا",
        "en_n": "Venezuelan",
        "ar_n": "فنزويلي",
    ],
    [
        "en": "Vietnam",
        "es": "Vietnam",
        "zh": "越南",
        "locale": "VN",
        "code": 84,
        "ar": "فيتنام",
        "en_n": "Vietnamese",
        "ar_n": "فيتنامي",
    ],
    [
        "en": "Yemen",
        "es": "Yemen",
        "zh": "也门",
        "locale": "YE",
        "code": 967,
        "ar": "اليمن",
        "en_n": "To whom",
        "ar_n": "اليمن",
    ],
    [
        "en": "Zimbabwe",
        "es": "Zimbabue",
        "zh": "津巴布韦",
        "locale": "ZW",
        "code": 263,
        "ar": "زمبابوي",
        "en_n": "Zimbabwe",
        "ar_n": "زمبابوي",
    ],
    [
        "en": "Zambia",
        "es": "Zambia",
        "zh": "赞比亚",
        "locale": "ZM",
        "code": 260,
        "ar": "زامبيا",
        "en_n": "Zambiani",
        "ar_n": "زامبياني",
    ]
    ] as [[String:Any]]

